### ISSUE TITLE
make install doesn't work on ubuntu 16.04

### ISSUE THREAD

**Issue by Minthos** [tobixen/thrash-protect#13]
```bash
~/Downloads/thrash-protect-master$ sudo make install
[sudo] password for user: 
install "thrash-protect.py" """/usr/sbin/thrash-protect"
if [ -d """/lib/systemd/system" ]; then install systemd/thrash-protect.service """/lib/systemd/system" ; \
        elif [ -d """/usr/lib/systemd/system" ]; then install systemd/thrash-protect.service """/usr/lib/systemd/system" ; fi
if [ -d """/etc/init" ]; then install upstart/thrash-protect.conf """/etc/init/thrash-protect.conf" ; fi
[ -d """/usr/lib/systemd/system" ] || [ -d """/etc/init" ] || [ -d """/lib/systemd/system" ] || install systemv/thrash-protect """/etc/init.d/thrash-protect"
```

**Comment by tobixen** [comment]
The output seems weird, but still it seems to be doing the job, it installs the files it's supposed to install.  Actually, more than what it's supposed to install; newer ubuntu releases supports both systemd and upstart, probably there should be another "elif" instead of "if" there, we probably shouldn't install the upstart config file if systemd exists.

**Comment by Minthos** [comment]
Oh you're right, I made a typo when I tried to start the service and it didn't show up in `service --status-all`
